use homelessness;

ALTER TABLE abbr
CHANGE ï»¿State State text;

CREATE TABLE data2007(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2007.csv'
INTO TABLE data2007
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

CREATE TABLE data2008(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2008.csv' INTO TABLE data2008 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2009(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2009.csv' INTO TABLE data2009 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2010(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2010.csv' INTO TABLE data2010 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2011(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2011.csv' INTO TABLE data2011 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2012(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2012.csv' INTO TABLE data2012 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2013(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2013.csv' INTO TABLE data2013 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2014(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2014.csv' INTO TABLE data2014 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2015(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2015.csv' INTO TABLE data2015 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2016(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2016.csv' INTO TABLE data2016 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2017(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2017.csv' INTO TABLE data2017 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2018(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2018.csv' INTO TABLE data2018 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2019(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2019.csv' INTO TABLE data2019 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TABLE data2020(Year int, State varchar(6), Overall_Homeless int, Overall_Under_18 int, Overall_18_to_24 int, Overall_Over_24 int, Overall_Homeless_Individuals int, Overall_Homeless_People_in_Families int, Overall_Hispanic_Latino int, Overall_White int, Overall_African_American int, Overall_Asian int, Overall_American_Indian	int, Overall_Pacific_Islander int, Overall_Multiple_Races int, Individual_Hispanic_Latino int, Individual_White int, Individual_African_American int, Individual_Asian int, Individual_American_Indian	int, Individual_Pacific_Islander int, Individual_Multiple_Races	int, People_In_Families_Hispanic_Latino int, People_In_Families_White int, People_In_Families_African_American int, People_In_Families_Asian int, People_In_Families_American_Indian int, People_In_Families_Pacific_Islander int, People_In_Families_Multiple_Races int, Overall_Homeless_Veterans int);
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/data2020.csv' INTO TABLE data2020 FIELDS TERMINATED BY ',' IGNORE 1 ROWS;

CREATE TEMPORARY TABLE final(
SELECT * 
FROM data2007
UNION SELECT * FROM data2008
UNION SELECT * FROM data2009
UNION SELECT * FROM data2010
UNION SELECT * FROM data2011
UNION SELECT * FROM data2012
UNION SELECT * FROM data2013
UNION SELECT * FROM data2014
UNION SELECT * FROM data2015
UNION SELECT * FROM data2016
UNION SELECT * FROM data2017
UNION SELECT * FROM data2018
UNION SELECT * FROM data2019
UNION SELECT * FROM data2020);

SELECT * FROM final;

SHOW VARIABLES LIKE "secure_file_priv";